### PR TITLE
Added support for Setting filters + sample filter for os version and device types

### PR DESCRIPTION
**Pull request by urish**
Setting Filters let you pre-filter the settings displayed in the IASKAppSettingsViewController. This is very useful if you need to display certain settings only on newer OS version, specific device type, or on special situations (such as after performing an in-app purchase).

### CODE REVIEW

**Comment by diederich** [comment]
Hey Uri,

thanks for submitting the pull request. This looks somewhat cleaner than my previous approach: https://github.com/diederich/InAppSettingsKit/tree/prototypes/filteredSettings

Just had a quick look on it. Does this approach also work with child view controllers?

**Comment by urish** [comment]
Hi, 

I am using it with a single view controller in my application (Zampona), but if it's desired I can have a look how to make it work with child view controllers.

All the best,
Uri

**Comment by urish** [comment]
Any updates?

**Comment by diederich** [comment]
Hm, not yet. My current implementation works (including childviewcontrollers) with the approach in https://github.com/diederich/InAppSettingsKit/tree/prototypes/filteredSettings
But I'm probably going look into this when I'm working on that part again. In the meantime you might want to present this approach to the original repo at https://github.com/futuretap/InAppSettingsKit

**Comment by urish** [comment]
Closing due to inactivity.

**Pull request closed without merging**
